# Generated by Django 4.2.5 on 2023-10-01 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='uncategorised', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
